### ISSUE TITLE
Share datasets

### ISSUE THREAD

**Issue by khaerulumam42** [jatana-research/Text-Classification#1]
Hello, this report so cool. I never imagined that CNN have great results on text classification. I wanna to try reproduce and maybe add other parameters like dropout to make more accurate, can you share the datasets? or script for scrapping datasets?

Thank you for your great explanation too on your blog!

**Comment by goodrahstar** [comment]
Hey @khaerulumam42 ,
Thanks for your appreciation. We would love to see if you can extend this work with your experimental reports. Unfortunately, we cannot share our data as its the companies policy.

But you can look here for similar kind of datasets.
https://toolbox.google.com/datasetsearch/search?query=%20Multi-Label%20Text%20Classification&docid=OTq4grGO00qZhYfDAAAAAA%3D%3D

Best,
RK

**Comment by khaerulumam42** [comment]
Okay i see. Its okay, thank you @goodrahstar :+1:
