### ISSUE TITLE
Typo in CNN.ipynb

### ISSUE THREAD

**Issue by parcar** [jatana-research/Text-Classification#5]
for idx in range(data_train.message.shape[0]):
        text = BeautifulSoup(data_train.message[idx])
        texts.append(clean_str(str(text.get_text().encode())))
    
    for idx in data_train['class']:
        labels.append(idx)

Should be:
    
    for idx in range(df.message.shape[0]):
        text = BeautifulSoup(df.message[idx])
        texts.append(clean_str(str(text.get_text().encode())))
    
    for idx in df['class']:
        labels.append(idx)

(In the CNN code)

**Comment by goodrahstar** [comment]
Thanks for pointing the type @parcar . [FIXED]

**Comment by leleyi** [comment]
where is the train_data?
